"use client";

import { useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence, Variants } from "framer-motion";
import {
  Sparkles,
  ChevronDown,
  ArrowRight,
  Map,
  Film,
  BookOpen,
  MessageCircle,
  Users,
  Ruler,
  Settings,
  BarChart3,
  Code2,
} from "lucide-react";

interface DemoStep {
  id: number;
  title: string;
  description: string;
  repoId: string;
  path: string;
  Icon: React.ComponentType<{ className?: string }>;
  details: string[];
}

const DEMO_STEPS: DemoStep[] = [
  {
    id: 1,
    title: "Explore the Architecture Map",
    description:
      "See the full system architecture of an Express.js e-commerce API — modules, dependencies, and tech stack — all auto-generated by AI.",
    repoId: "demo/express-shop",
    path: "/dashboard/demo%2Fexpress-shop",
    Icon: Map,
    details: [
      "React Flow interactive node graph",
      "7 modules detected: API Gateway, Auth, Products, Orders, Payments, Database, Cache",
      "Dependency edges show data flow between modules",
      "Tech stack breakdown (Express, Prisma, PostgreSQL, Redis, Stripe)",
    ],
  },
  {
    id: 2,
    title: "Watch Animated Data Flows",
    description:
      "Step through an animated visualization of how an order is processed — from cart checkout through Stripe payment to webhook confirmation.",
    repoId: "demo/express-shop",
    path: "/dashboard/demo%2Fexpress-shop/animated",
    Icon: Film,
    details: [
      "3 pre-built animation sequences (Auth, Order, Data Pipeline)",
      "Click any node for an AI-generated plain-English explanation",
      "Multi-language support: Hindi, Tamil, Telugu, Kannada, Bengali, Marathi",
      "Fresher-friendly mode for beginners",
    ],
  },
  {
    id: 3,
    title: "Read Code Walkthroughs",
    description:
      "Follow AI-generated step-by-step walkthroughs of key features like authentication and order processing, linked to actual source files.",
    repoId: "demo/express-shop",
    path: "/dashboard/demo%2Fexpress-shop/walkthroughs",
    Icon: BookOpen,
    details: [
      "Pre-built walkthroughs: JWT Auth Flow, Order Pipeline, Database Schema",
      "Each step references specific files and line ranges",
      "Ask a custom question to generate a new walkthrough on the fly",
      "Great for onboarding new team members",
    ],
  },
  {
    id: 4,
    title: "Ask Questions (AI Q&A)",
    description:
      "Ask natural language questions about the codebase and get context-aware answers with relevant file references and follow-up suggestions.",
    repoId: "demo/express-shop",
    path: "/dashboard/demo%2Fexpress-shop/qa",
    Icon: MessageCircle,
    details: [
      'Try: "How does authentication work?"',
      'Try: "How are orders processed?"',
      'Try: "What is the database schema?"',
      "Answers include relevant files and related question suggestions",
    ],
  },
  {
    id: 5,
    title: "Track Team Progress",
    description:
      "See how team members are progressing through onboarding — skill radars, timelines, leaderboard, and module completion grids.",
    repoId: "demo/express-shop",
    path: "/dashboard/demo%2Fexpress-shop/team",
    Icon: Users,
    details: [
      "3 team members with different progress levels",
      "Skill radar chart showing per-area competency",
      "Leaderboard with medals and time tracking",
      "Individual progress timelines",
    ],
  },
];

const fadeUp: Variants = {
  hidden: { opacity: 0, y: 16 },
  visible: (i: number = 0) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.06, duration: 0.4, ease: [0.22, 1, 0.36, 1] },
  }),
};

const stagger: Variants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.08 } },
};

export default function DemoScriptPage() {
  const [activeStep, setActiveStep] = useState(0);

  return (
    <div className="min-h-screen bg-brand-bg text-brand-text font-body selection:bg-brand-DEFAULT/30">
      {/* ─── HEADER ─── */}
      <header className="border-b border-brand-border bg-brand-bg/90 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link href="/" className="flex items-center gap-3 group">
              <div className="w-8 h-8 bg-brand-DEFAULT rounded-sm flex items-center justify-center">
                <Code2 className="w-4 h-4 text-brand-bg" />
              </div>
              <span className="font-heading font-semibold text-xl tracking-tight">AutoDev</span>
            </Link>
            <span className="text-xs px-2.5 py-1 rounded-sm bg-brand-surface border border-brand-border text-brand-muted font-mono tracking-wide">
              Demo Script
            </span>
          </div>
          <Link
            href="/dashboard?demo=true"
            className="inline-flex items-center gap-2 px-5 py-2.5 bg-brand-text text-brand-bg hover:bg-brand-DEFAULT hover:text-brand-bg rounded-sm font-semibold transition-colors duration-200 text-sm"
          >
            Open Dashboard <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </header>

      {/* ─── HERO ─── */}
      <motion.section
        initial="hidden"
        animate="visible"
        variants={stagger}
        className="max-w-4xl mx-auto px-6 py-16 text-center"
      >
        <motion.h1 variants={fadeUp} className="text-5xl md:text-6xl font-heading font-bold mb-6 tracking-tight leading-tight">
          AutoDev Demo <span className="text-brand-muted italic">Walkthrough</span>
        </motion.h1>
        <motion.p variants={fadeUp} custom={1} className="text-brand-muted font-mono text-sm md:text-base max-w-2xl mx-auto mb-6 leading-relaxed">
          Follow this 5-step guided demo to see how AutoDev transforms codebase
          onboarding. Each step links directly to a live demo page with
          pre-analyzed data — no installation required.
        </motion.p>
        <motion.div variants={fadeUp} custom={2} className="inline-flex items-center gap-2 px-3 py-1 rounded-sm border border-brand-border bg-brand-surface font-mono text-xs text-brand-muted mt-2">
          AI for Bharat Hackathon 2026 &middot; Student Track &middot; Team AutoDev
        </motion.div>
      </motion.section>

      {/* ─── STEPS ─── */}
      <motion.section
        initial="hidden"
        animate="visible"
        variants={stagger}
        className="max-w-4xl mx-auto px-6 pb-24"
      >
        <div className="grid gap-4">
          {DEMO_STEPS.map((step, index) => {
            const isActive = activeStep === index;

            return (
              <motion.div
                key={step.id}
                variants={fadeUp}
                custom={index}
                className={`transition-all duration-300 border rounded-sm overflow-hidden ${
                  isActive
                    ? "bg-brand-surface border-brand-DEFAULT/30"
                    : "bg-brand-card border-brand-border hover:border-brand-muted/50"
                }`}
              >
                <button
                  type="button"
                  onClick={() => setActiveStep(isActive ? -1 : index)}
                  className="w-full text-left p-6 flex flex-col sm:flex-row items-start sm:items-center gap-5 cursor-pointer"
                >
                  <div
                    className={`flex-shrink-0 w-12 h-12 rounded-sm flex items-center justify-center transition-colors duration-200 ${
                      isActive
                        ? "bg-brand-DEFAULT text-brand-bg"
                        : "bg-brand-surface border border-brand-border text-brand-muted"
                    }`}
                  >
                    <step.Icon className="w-5 h-5" />
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-xs text-brand-DEFAULT font-mono font-medium tracking-wide">
                        STEP {step.id}/5
                      </span>
                    </div>
                    <h3 className="text-xl font-heading font-semibold mb-1 text-brand-text">{step.title}</h3>
                    <p className="text-brand-muted font-body text-sm leading-relaxed">{step.description}</p>
                  </div>

                  <ChevronDown
                    className={`hidden sm:block w-5 h-5 text-brand-muted transition-transform duration-200 flex-shrink-0 ${
                      isActive ? "rotate-180" : ""
                    }`}
                  />
                </button>

                <AnimatePresence>
                  {isActive && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
                      className="overflow-hidden bg-brand-surface"
                    >
                      <div className="px-6 pb-6 pt-0">
                        <div className="border-t border-brand-border/50 pt-5 sm:ml-[4.25rem]">
                          <h4 className="text-xs font-mono font-medium text-brand-muted uppercase tracking-wider mb-4">
                            What you&apos;ll see
                          </h4>
                          <ul className="space-y-3 mb-6 bg-brand-bg border border-brand-border/50 rounded-sm p-5">
                            {step.details.map((detail, i) => (
                              <li
                                key={i}
                                className="flex items-start gap-3 font-mono text-sm text-brand-muted"
                              >
                                <span className="text-brand-DEFAULT mt-0.5">{"//"}</span>
                                {detail}
                              </li>
                            ))}
                          </ul>
                          <Link
                            href={step.path}
                            className="inline-flex items-center gap-2 px-6 py-3 bg-brand-DEFAULT hover:bg-white text-brand-bg rounded-sm text-sm font-semibold transition-colors duration-200"
                          >
                            Launch Step {step.id} <ArrowRight className="w-4 h-4" />
                          </Link>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>
      </motion.section>

      {/* ─── ADDITIONAL EXPLORATION ─── */}
      <section className="bg-brand-surface border-t border-brand-border py-20 px-6">
        <div className="max-w-4xl mx-auto space-y-12">
          
          <motion.div variants={fadeUp} className="space-y-6">
            <h3 className="text-2xl font-heading font-semibold border-b border-brand-border pb-4">Also Explore</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
              {[
                { href: "/dashboard/demo%2Fexpress-shop/conventions", Icon: Ruler, title: "Coding Conventions", desc: "AI-detected naming, structure, and error handling patterns" },
                { href: "/dashboard/demo%2Fexpress-shop/env-setup", Icon: Settings, title: "Env Setup Guide", desc: "Auto-generated prerequisites, install steps, and verification" },
                { href: "/dashboard/demo%2Fexpress-shop/progress", Icon: BarChart3, title: "My Progress", desc: "Skill radar, timeline, and module completion tracking" },
              ].map(({ href, Icon, title, desc }) => (
                <Link
                  key={href}
                  href={href}
                  className="group p-5 bg-brand-card border border-brand-border hover:border-brand-DEFAULT rounded-sm transition-colors duration-200"
                >
                  <div className="flex items-center gap-3 mb-3">
                    <Icon className="w-5 h-5 text-brand-DEFAULT" />
                    <p className="font-heading font-semibold text-brand-text">{title}</p>
                  </div>
                  <p className="font-mono text-brand-muted text-xs leading-relaxed">{desc}</p>
                </Link>
              ))}
            </div>
          </motion.div>

          <motion.div variants={fadeUp} className="space-y-6">
            <h3 className="text-2xl font-heading font-semibold border-b border-brand-border pb-4">Try Other Demo Repos</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              <Link
                href="/dashboard/demo%2Freact-dashboard"
                className="group p-6 bg-brand-card border border-brand-border hover:border-brand-DEFAULT rounded-sm transition-colors duration-200"
              >
                <p className="font-heading font-semibold text-lg mb-2 group-hover:text-brand-DEFAULT transition-colors">React Dashboard</p>
                <div className="flex gap-2 font-mono text-xs text-brand-muted">
                  <span className="text-brand-DEFAULT">{"├─"}</span> Next.js 14 + Supabase + Tailwind CSS (134 files)
                </div>
              </Link>
              <Link
                href="/dashboard/demo%2Fpython-ml-api"
                className="group p-6 bg-brand-card border border-brand-border hover:border-brand-DEFAULT rounded-sm transition-colors duration-200"
              >
                <p className="font-heading font-semibold text-lg mb-2 group-hover:text-brand-DEFAULT transition-colors">Python ML API</p>
                <div className="flex gap-2 font-mono text-xs text-brand-muted">
                  <span className="text-brand-DEFAULT">{"├─"}</span> FastAPI + MongoDB + scikit-learn (52 files)
                </div>
              </Link>
            </div>
          </motion.div>

        </div>
      </section>

      {/* ─── FOOTER ─── */}
      <footer className="border-t border-brand-border py-8 px-6 text-center">
        <p className="font-mono text-xs text-brand-muted">
          © 2026 AutoDev Inc. All rights reserved.
        </p>
      </footer>
    </div>
  );
}
